name: Python checks
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  checks:
    strategy:
      matrix:
        check:
          - style
          - static_typing
          - linter
          - complexity
          - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: poetry install
      - name: Check ${{ matrix.check }}
        run: sh -e -u -x .ci/python_check_${{ matrix.check }}.sh furry_barnacle tests
